services:
  kafka-1:
    image: apache/kafka:4.2.0
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "controller, broker"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093"

      KAFKA_LISTENERS: \
        PLAINTEXT://0.0.0.0:9092, \
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: \
        PLAINTEXT:PLAINTEXT, \
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "NKSDJNfk4k4j21112FD"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --list -bootstrap-server localhost:9092 2>&1 | grep -q 'Exception\\|Error\\|WARN' && exit 1 || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/lib/kafka/data
    networks:
      - kafka-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.6
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      kafka-1:
        condition: service_healthy
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://localhost:8081/subjects
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./schema-registry-data:/bitnami
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: on-failure
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on:
      kafka-1:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "8095:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: iot
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    networks:
      - kafka-network


networks:
  kafka-network:
    driver: bridge
