spring:
  application:
    name: "2-events-collector-service"

kafka:
  bootstrapServers: "not-setted"
  schemaRegistryUrl: "not-setted"
  kafkaTopicList:
    - name: "RawEvents"
      groupId: "events-collector-group"
      partitions-count: 1
      replicas-count: 1
    - name: "ProcessedEvents"
      groupId: "events-collector-group"
      partitions-count: 1
      replicas-count: 1
